checkbox-dz
js-tasks-ru/htmlcss-20220519_afonin-andrey-sergeevich pull request #12
Opened 2022-06-16 09:53 UTC by buldogic

2022-06-16 09:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-17 21:22 UTC, GSemikozov requested changes

2022-06-17 21:22 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    margin: 12px;
марджины на уровне блока не задаем

2022-06-17 21:22 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__disabled{
строки 59-64 удалим, лишнее. При disabled нужно просто `.checkbox__imput:disabled ~ .checkbox__state { pointer-events: none }`

2022-06-20 08:45 UTC, buldogic commented on 07-lection5/01-checkbox/checkbox.css
> +    margin: 12px;
убрал

2022-06-20 08:45 UTC, buldogic commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__disabled{
исправил

2022-07-04 15:54 UTC, GSemikozov approved these changes

2022-07-04 15:54 UTC, merged