06-01-avatar-dz
js-tasks-ru/htmlcss-20220519_afonin-andrey-sergeevich pull request #15
Opened 2022-06-16 09:55 UTC by buldogic

2022-06-16 09:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-17 21:30 UTC, GSemikozov requested changes

2022-06-17 21:30 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar{
много лишних элементов. На самом деле у нас только .avatar + .avatar__img внутри

2022-06-21 14:41 UTC, GSemikozov requested changes

2022-06-21 14:41 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    font-family: 'Roboto';
все стили лишние - у нас ведь нет текста внутри и при этом размеры блока ка раз таки должны быть фиксированные)
так здесь - фиксируем размеры как в макете..

2022-06-21 14:41 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: 160px;
..а. здесь тогда растягиваем ширину и высоту на 100% по родителю

2022-06-22 12:14 UTC, buldogic commented on 06-lection4/01-avatar/avatar.css
> +    font-family: 'Roboto';
переделал

2022-06-22 12:14 UTC, buldogic commented on 06-lection4/01-avatar/avatar.css
> +    width: 160px;
переделал

2022-06-24 19:09 UTC, merged