dz 02-accordion
js-tasks-ru/htmlcss-20220519_afonin-andrey-sergeevich pull request #3
Opened 2022-05-24 16:38 UTC by buldogic

решение задания с аккардионом

2022-05-24 16:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-24 18:31 UTC, GSemikozov requested changes

2022-05-24 18:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
здесь пока 1 общий комментарий: классы надо оформить по БЭМ, селекторы тегов и вложенные селекторы не используем. Сформировать корректную структуру / разметку компонента с учетом классов

2022-05-24 20:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-25 13:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-25 14:04 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
переделал полностью все, едиственное не очень понял как поставить стрелку справа. она у меня все время ломается и весит где ей удобно))) убрал ее вообще

2022-05-26 15:21 UTC, GSemikozov requested changes

2022-05-26 15:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +*{
ай-яй-яй, глобальные стили в файле стилей компонента ;)

2022-05-26 15:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details .accordion__item::-webkit-details-marker {
лишняя вложенность не нужно, просто .accordion__item::-webkit-details-marker

2022-05-26 15:21 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__details" >
блок не может быть одновременно и исвоих элементом (как родитель не может быть своим ребенком). Элементы - всегда вложенные в блок.

2022-05-26 15:21 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__details" >
блок один - а внутри 3 элемента

2022-05-26 15:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 24px 419px 24px 32px;
лишнее. Если айтемы будут завернуты в .accordion - тогда просто margin-bottom: 8px

2022-05-26 15:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +      width: 579px;
ширину и высоту не нужно ограничивать - удалим

2022-05-26 15:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 8px auto;
тут нужны паддинги

2022-05-26 15:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 16px 32px 32px;
и тут

2022-05-26 19:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-26 19:13 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +*{
убрал

2022-05-26 19:15 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details .accordion__item::-webkit-details-marker {
я так понимаю это в сафари стрелку убирает?

2022-05-26 19:17 UTC, buldogic commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__details" >
не нашел этого в коде)

2022-05-26 19:44 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +    margin: 8px auto;
исправил

2022-05-26 19:45 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +    margin: 16px 32px 32px;
убрал margin и добавил padding

2022-05-26 19:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-26 19:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-27 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details .accordion__item::-webkit-details-marker {
у браузеров которые используют webkit движок

2022-05-27 18:55 UTC, GSemikozov requested changes

2022-05-27 18:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 419px 24px 32px;
справа будет такой же как и слева, то есть 32

2022-05-27 18:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +      margin-bottom: 8px;
на уровне блоке марджины не задаем

2022-05-27 18:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details[open] .accordion__item::after {
а зачем нам здесь какие-то стили для ::after ?)

2022-05-27 18:55 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <details class=" accordion accordion__details" >
вот так делать `<details class="accordion accordion__details" >` - ошибка, выше писал, что  "блок не может быть одновременно и исвоих элементом (как родитель не может быть своим ребенком). Элементы - всегда вложенные в блок." Это означает, что нужно создать div с классом accordion, а в него положить все details, которые являются элементами аккордиона и должны иметь класс .accordion__item (которому, как элементу, отступ снизу как раз таки задавать можно)

2022-05-27 18:55 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <summary class="accordion accordion__item">
и здесь - зачем дублируем класс accordion? Это же элемент аккордина accordion__item (на самом деле должен быть accordion__title / accordion__summary, видимо при именовании классов возникла путаница)

2022-05-30 11:32 UTC, buldogic commented on 03-lection1/02-accordion/index.html
> +                <summary class="accordion accordion__item">
да с классами пока проблема

2022-05-30 11:33 UTC, buldogic commented on 03-lection1/02-accordion/index.html
> +            <details class=" accordion accordion__details" >
вроде понял

2022-05-30 11:33 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details[open] .accordion__item::after {
хотел что бы когда открывался не менялся отступ от текста и accordion item

2022-05-30 11:34 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +      margin-bottom: 8px;
да убрал отступы

2022-05-30 11:34 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 419px 24px 32px;
хорошо

2022-05-31 13:06 UTC, GSemikozov requested changes

2022-05-31 13:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion:last-child {
лишнее, можно удалить

2022-05-31 13:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 32px;
при состоянии accordion__item[open] паддинг снизу будет 16

2022-05-31 22:15 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +    height: auto;
убрал

2022-05-31 22:17 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +.accordion:last-child {
так это же в задачнике стоит, я думал что надо добавлять

2022-05-31 22:17 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +    height: auto;
убрал

2022-05-31 22:21 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 32px;
не очень понял к чему это? надо сделать чтобы при развертывание паддинг был 16px?

2022-05-31 22:21 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +    margin: 24px 419px 24px 32px;
изменил

2022-05-31 22:22 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +      width: 579px;
хорошо

2022-06-17 21:09 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 32px;
ага
<img width="454" alt="Screenshot 2022-06-18 at 00 09 28" src="https://user-images.githubusercontent.com/6191270/174401448-093baa2c-b863-471f-bc33-1db028bb1192.png">

2022-06-20 10:32 UTC, buldogic commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 32px;
сделал

2022-06-21 14:22 UTC, merged