look
js-tasks-ru/htmlcss-20220519_afonin-andrey-sergeevich pull request #6
Opened 2022-05-30 13:44 UTC by buldogic

не понимаю почему у меня не встают в колонку линии рядом с кругом

2022-05-30 13:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 15:34 UTC, GSemikozov requested changes

2022-05-30 15:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    border: 1px solid #000;
цвет не по дизайну + надо добавить радиус и паддинги

2022-05-30 15:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px 24px;
чтобы потом паддинги не дублировать в каждом дочернем эелменте

2022-05-30 15:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    background-color: grey;
цвет не по дизайну

2022-05-30 15:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line{
.skeleton__line уже есть

2022-05-30 15:45 UTC, buldogic commented on 04-lection2/02-skeleton/skeleton.css
> +    border: 1px solid #000;
исправил

2022-05-30 15:45 UTC, buldogic commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px 24px;
исправил

2022-05-30 15:45 UTC, buldogic commented on 04-lection2/02-skeleton/skeleton.css
> +    background-color: grey;
исправил

2022-05-30 15:48 UTC, buldogic commented on 04-lection2/02-skeleton/skeleton.css
> +.line{
если это убрать то тогда линии рядом с кругом уйдут

2022-05-31 22:11 UTC, buldogic commented on 04-lection2/02-skeleton/skeleton.css
> +.line{
исправил

2022-06-17 21:11 UTC, GSemikozov approved these changes

2022-06-17 21:11 UTC, merged