dz histogram
js-tasks-ru/htmlcss-20220519_afonin-andrey-sergeevich pull request #7
Opened 2022-05-30 14:52 UTC by buldogic

2022-05-30 14:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 15:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-30 15:36 UTC, GSemikozov requested changes

2022-05-30 15:36 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border-radius: 8px;
здесь не хватает паддингов и цвет не по макету

2022-05-30 15:36 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__p{
класс по названию тега все равно что использовать селектор тега )
в общем, нужно поправить классы, сделать их более семантичными, например __title, __subtitle

2022-05-30 15:36 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
можно сразу указать на .histogram

2022-05-30 15:36 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <svg class="mySvg" width="299" height="50" viewBox="0 0 299 50" fill="none" xmlns="http://www.w3.org/2000/svg">
хитро, но - нет, это надо сверстать отдельными стилизованными хтмл элементами)

2022-05-30 15:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 15:53 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +    border-radius: 8px;
исправил

2022-05-30 15:54 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
исправил

2022-05-30 15:54 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
но мы же блоку не задаем размеры

2022-05-31 13:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
этот модификатор все равно модифицирует блок. 
блоку задавать размеры можно, тогда когда это актуально, как в случае с компонентом Аватар

2022-05-31 22:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-31 22:24 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +.histogram__p{
переделал

2022-05-31 22:24 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
исправил

2022-05-31 22:55 UTC, buldogic commented on 04-lection2/01-histogram/index.html
> +                <svg class="mySvg" width="299" height="50" viewBox="0 0 299 50" fill="none" xmlns="http://www.w3.org/2000/svg">
переделал

2022-05-31 22:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-17 21:15 UTC, GSemikozov requested changes

2022-06-17 21:15 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
жестко фиксировать размеры не стоит, блок должен быть адаптивным

2022-06-17 21:15 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 24px 15px;
чтобы не писать однотипные отступы здесь и у .histogram__botton - лучше задать сразу на уровне .histogram

2022-06-17 21:15 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__column{
.histogram__chart

2022-06-17 21:15 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.column__item{
.histogram__chart-item

2022-06-17 21:15 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
вместо ширины flex-basis: 9px + flex-grow: 1 (протестировать когда в чарте будет всего 1-2 колонки)

2022-06-17 21:15 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 1px;
либо margin-right: 1px либо gap: 1px на уровне родителя

2022-06-20 10:18 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
исправил

2022-06-20 10:24 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 24px 15px;
переделал

2022-06-20 10:24 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +.histogram__column{
переименовал

2022-06-20 10:24 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +.column__item{
переименовал

2022-06-20 10:24 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
посмотрел, исправил

2022-06-20 10:24 UTC, buldogic commented on 04-lection2/01-histogram/histogram.css
> +    margin: 1px;
исправил

2022-06-21 14:23 UTC, GSemikozov approved these changes

2022-06-21 14:23 UTC, merged