05-01-tooltip-dz
js-tasks-ru/htmlcss-20220519_afonin-andrey-sergeevich pull request #9
Opened 2022-06-02 10:19 UTC by buldogic

2022-06-02 10:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-02 15:46 UTC, GSemikozov requested changes

2022-06-02 15:46 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: 130%;
нужно как на лекции, только наоборот: `bottom: calc(100% + 8px)`

2022-06-02 15:46 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body{
глобальные / вспомогательные стили в файле стилей компонента никогда не описываем. Можно заинлайнить прямо на body самой страницы (она ведь только для примера)

2022-06-02 15:49 UTC, buldogic commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: 130%;
я так сделал и у меня окно ушло вниз под картинку

2022-06-02 15:51 UTC, buldogic commented on 05-lection3/01-tooltip/tooltip.css
> +body{
ну я так сделал что бы просто было видно или просто отступы добавить в tooltip?

2022-06-17 21:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    bottom: 130%;
это потому, что сверху нет пространства, поверх которого отобразится всплывашка. В таких случаях внешнее позиционирование задается не через сам блок, а через родителя и класс-микс, либо - можно произвольную обертку добавить и описать любые произвольные стили в теге style страницы с решением задачи

2022-06-17 21:19 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body{
это понятно, что стили просто вспомогательные - но такие стили мы никогда не описываем на уровне компонента. Нужно их просто перенести в другое место, например в тег style хтмл страницы с решением

2022-06-20 10:00 UTC, buldogic commented on 05-lection3/01-tooltip/tooltip.css
> +body{
сделал

2022-06-21 14:36 UTC, merged